package com.application.model.mongo;

import com.application.dto.AudioDto;
import com.application.util.CloudProvider;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.UUID;

@Getter
@Setter
@Document(collection = "user_audios")
public class UserAudioMongoModal {
    private final LocalDateTime createdAt = LocalDateTime.now(); // Maps to image_created_at
    private final String cloudProvider = CloudProvider.AMAZON_S3.toString();
    @Id
    private String id; // Auto-generated by MongoDB
    @NotNull
    private String userUUID;
    private String publicUrl;
    @NotNull
    @Indexed(unique = true)
    private String fileName = userUUID + "." + UUID.randomUUID();
    private Long fileSize;
    private String format;
    private LocalDateTime expireAt;
    private Long lengthInSecond;

    public AudioDto mapToAudioDto() {
        AudioDto audioDto = new AudioDto();
        audioDto.set_id(id);
        audioDto.setUrl(publicUrl);
        audioDto.setOwner_UUID(userUUID);
        audioDto.setLength_in_second(lengthInSecond);
        return audioDto;
    }

}
